export const weatherTypes = [
  {
    type:"clouds",
    img:["./pictures/clouds.png","./pictures/clouds.png"],
    icon:["☁️","☁️"],
    name:"Облачно",
  },
  {
    type:"rain",
    img:["./pictures/rain.png","./pictures/rain.png"],
    icon:["🌧️","🌧️"],
    name:"Дождь",
  },
  {
    type:"snow",
    img:["./pictures/snow.png","./pictures/snow.png"],
    icon:["❄️","❄️"],
    name:"Снегопад",
  },
  {
    type:"sun",
    img:["./pictures/moon.png","./pictures/sun.png"],
    icon:["🌙","☀️"],
    name:"Ясно",
  },
  {
    type:"sunclouds",
    img:["./pictures/moonclouds.png","./pictures/sunclouds.png"],
    icon:["⛅","⛅"],
    name:"Переменная облачность",
  },
]